name: Main Workflow
on: [push]
jobs:
  build-gcc:
    name: Build GCC
    strategy:
      matrix:
        gcc-version: [5, 6, 7, 8, 9]
    runs-on: ubuntu-latest
    container: gcc:${{ matrix.gcc-version }}
    steps:
      - uses: actions/checkout@v1
      - run: make
  build-clang:
    name: Build Clang
    strategy:
      matrix:
        clang-version: [3, 4, 5, 6, 7]
    runs-on: ubuntu-latest
    container: silkeh/clang:${{ matrix.clang-version }}
    steps:
      - uses: actions/checkout@v1
      - run: CC=clang make

