sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5-dev"
  - "pypy"
  - "pypy3"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install twine
script: coverage run --source=pconvert setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: IKGSjx+IGgz5d+kbQrhkbATORlfmxU4WMj2KQsuIQuQS1cO6I2r/8q6GhgXoy93Q+FwjZ4JpAeSidVYHNV+GpN2PIDw+bra5BZQvEupUq35j2tahHPhn3dn2D1HxX8Y/C+UnQX/PRJjXSEyKdTeCR+cRUILUQwrH8ngpXJBlsiI=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
