sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5-dev"
  - "pypy"
  - "pypy3"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install twine
script: coverage run --source=pconvert setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: B5Ko+u0fT8q/w1BPAxaElkbhIJ4JFGrIVBLOvcXiH4EW6OkOm/Mq9ETZEZbZAiD4I3R7LjDc/Um6QwaLAJXWhxF0AHWJBkdDKH5yAEZit+c6tF+6ywhPBDm8fUcv87g1f/l5fHLQsn7K0Qhif0PXo4iIyTdPa6nKSp4GD8Sh+IA2cPCtqyXC6kSeL2TAP1m/bO9rsJZNCIXZUMzVP8bWtKfU6aYSDlOfveJiJRErurXLm4LOxW4R8tnTS+RSPsI6pyieB2vOrxYes1fcJWehLdXtkn+auaDL6XJnj5d/yXJzXX0erJOIpJMMaPHpOa7ivDigHA1FM0NAYltOHraODH3eV+pCdLU1XYqKVk9uJbQVWeS+bI6gdgLon4pAYL1KBhV2+D8w7jljc19qAJNrPFFB7wYUlCypJqTMuD52PY5ZHVcXjnspTXDFXFyE5alt4SDLMWrQmLcrbbb/xVd+o4WDI1FLVE7E2AjNoSnMBMvA7WiFa4nCM0/yfZhgP9VK2s3QAg9U5S2S3c5fL0c39XyQX9TpRJ6RTdgQe3xXiPqZzhZPtxvrFzczHE+9HNqD/WpFN8g/t94o+X2rQWHpxMkNps6cRPUYio5KIYgJhVG1szPluEBFTpXY2HdP9l9JEAXYD3c2oxcIpbBXwxlaDxKqjoUHl8Z0glOEwLcSqmk=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
