name: Main Workflow
on: [push]
jobs:
  build-gcc:
    name: Build GCC
    strategy:
      matrix:
        gcc-version: [5, 6, 7, 8, 9]
    runs-on: ubuntu-latest
    container: gcc:${{ matrix.gcc-version }}
    steps:
      - uses: actions/checkout@v1
      - run: apt-get update && apt-get install -y -q wget libssl-dev
      - run: wget https://github.com/Kitware/CMake/releases/download/v3.16.6/cmake-3.16.6.tar.gz && tar -zxvf cmake-3.16.6.tar.gz && cd cmake-3.16.6 && ./bootstrap && make && make install
      - run: apt-get update && apt-get install -y -q python python-pip python-dev libpng-dev
      - run: pip install --upgrade conan urllib3
      - run: conan install . --build
      - run: make
      - run: ./pconvert version
  build-clang:
    name: Build Clang
    strategy:
      matrix:
        clang-version: [3, 4, 5, 6, 7]
    runs-on: ubuntu-latest
    container: silkeh/clang:${{ matrix.clang-version }}
    steps:
      - uses: actions/checkout@v1
      - run: apt-get update && apt-get install -y -q wget libssl-dev
      - run: wget https://github.com/Kitware/CMake/releases/download/v3.16.6/cmake-3.16.6.tar.gz && tar -zxvf cmake-3.16.6.tar.gz && cd cmake-3.16.6 && ./bootstrap && make && make install
      - run: apt-get update && apt-get install -y -q python python-pip python-dev libpng-dev wget libssl-dev
      - run: pip install --upgrade conan urllib3
      - run: conan install . --build
      - run: make CC=clang
      - run: ./pconvert version
