name: Main Workflow
on: [push]
jobs:
  build-gcc:
    name: Build GCC
    timeout-minutes: 30
    strategy:
      matrix:
        gcc-version: [5, 6, 7, 8, 9, 10, 11, 12]
    runs-on: ubuntu-latest
    container: gcc:${{ matrix.gcc-version }}
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          apt-get update && apt-get install -y -q wget libpng-dev
      - name: Build P(NG)Convert
        run: |
          make
      - name: Test P(NG)Convert
        run: |
          ./pconvert version
          ./pconvert benchmark assets/demo/
  build-clang:
    name: Build Clang
    timeout-minutes: 30
    strategy:
      matrix:
        clang-version: [3, 4, 5, 6, 7, 8, 10, 12, 14]
    runs-on: ubuntu-latest
    container: silkeh/clang:${{ matrix.clang-version }}
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          apt-get update && apt-get install -y -q wget libpng-dev
      - name: Build P(NG)Convert
        run: |
          make CC=clang
      - name: Test P(NG)Convert
        run: |
          ./pconvert version
          ./pconvert benchmark assets/demo/
  build-gcc-cmake:
    name: Build GCC CMake
    timeout-minutes: 30
    strategy:
      matrix:
        gcc-version: [7, 8, 9, 10, 11, 12]
    runs-on: ubuntu-latest
    container: gcc:${{ matrix.gcc-version }}
    steps:
      - uses: actions/checkout@v1
      - name: Build & Install CMake
        run: |
          apt-get update && apt-get install -y -q cmake
      - name: Build & Install Dependencies
        run: |
          apt-get update && apt-get install -y -q wget python python-dev libpng-dev
          wget https://bootstrap.pypa.io/pip/2.7/get-pip.py && python get-pip.py
          pip install --upgrade conan urllib3
          conan install . --build
      - name: Build P(NG)Convert
        run: |
          cmake .
          make
      - name: Test P(NG)Convert
        run: |
          ./bin/pconvert version
          ./bin/pconvert benchmark assets/demo/
  build-windows-cmake:
    name: Build Windows CMake
    timeout-minutes: 30
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build & Install Dependencies
        run: |
          pip3 install --upgrade conan urllib3
          conan install . --build
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build P(NG)Convert
        run: |
          cmake . -DCMAKE_CL_64=1 -DCMAKE_GENERATOR_PLATFORM=x64 -Ax64
          msbuild ALL_BUILD.vcxproj /P:Configuration=Release
      - name: Test P(NG)Convert
        run: |
          bin/pconvert version
          bin/pconvert benchmark ((Get-Item -Path ".\").FullName + "\assets\demo\")
  build-macos-cmake:
    name: Build macOS CMake
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build & Install Dependencies
        run: |
          export PATH=$PATH:/Library/Frameworks/Python.framework/Versions/2.7/bin
          pip3 install --upgrade "conan>1.50.0" "urllib3<1.27"
          conan install . --build
      - name: Build P(NG)Convert
        run: |
          cmake .
          make
      - name: Test P(NG)Convert
        run: |
          ./bin/pconvert version
          ./bin/pconvert benchmark assets/demo/
