name: Main Workflow
on: [push]
jobs:
  build-gcc:
    name: Build GCC
    strategy:
      matrix:
        gcc-version: [5, 6, 7, 8, 9]
    runs-on: ubuntu-latest
    container: gcc:${{ matrix.gcc-version }}
    steps:
      - uses: actions/checkout@v1
      - name: Build & Install CMake
        run: |
          apt-get update && apt-get install -y -q wget libssl-dev
          wget https://github.com/Kitware/CMake/releases/download/v3.16.6/cmake-3.16.6.tar.gz && tar -zxvf cmake-3.16.6.tar.gz && cd cmake-3.16.6 && ./bootstrap && make && make install
      - name: Build P(NG)Convert
        run: |
          apt-get update && apt-get install -y -q python python-pip python-dev libpng-dev
          pip install --upgrade conan urllib3
          conan install . --build
          make
          ./pconvert version
  build-clang:
    name: Build Clang
    strategy:
      matrix:
        clang-version: [3, 4, 5, 6, 7]
    runs-on: ubuntu-latest
    container: silkeh/clang:${{ matrix.clang-version }}
    steps:
      - uses: actions/checkout@v1
      - name: Build & Install CMake
        run: |
          apt-get update && apt-get install -y -q wget libssl-dev
          wget https://github.com/Kitware/CMake/releases/download/v3.16.6/cmake-3.16.6.tar.gz && tar -zxvf cmake-3.16.6.tar.gz && cd cmake-3.16.6 && ./bootstrap && make && make install
      - name: Build P(NG)Convert
        run: |
          apt-get update && apt-get install -y -q python python-pip python-dev libpng-dev wget libssl-dev
          pip install --upgrade conan urllib3
          conan install . --build
          make CC=clang
      - name: Test P(NG)Convert
        run: |
          ./bin/pconvert version
  build-gcc-cmake:
    name: Build GCC CMake
    strategy:
      matrix:
        gcc-version: [5, 6, 7, 8, 9]
    runs-on: ubuntu-latest
    container: gcc:${{ matrix.gcc-version }}
    steps:
      - uses: actions/checkout@v1
      - name: Build & Install CMake
        run: |
          apt-get update && apt-get install -y -q wget libssl-dev
          wget https://github.com/Kitware/CMake/releases/download/v3.16.6/cmake-3.16.6.tar.gz && tar -zxvf cmake-3.16.6.tar.gz && cd cmake-3.16.6 && ./bootstrap && make && make install
      - name: Build P(NG)Convert
        run: |
          apt-get update && apt-get install -y -q python python-pip python-dev libpng-dev
          pip install --upgrade conan urllib3
          conan install . --build
          cmake .
          make
      - name: Test P(NG)Convert
        run: |
          ./bin/pconvert version
  build-windows-cmake:
    name: Build Windows CMake
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build P(NG)Convert
        run: |
          pip install --upgrade conan urllib3
          conan install . --build
          cmake . -DCMAKE_CL_64=1 -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_GENERATOR_PLATFORM=x64 -Ax64 -Wno-dev
          msbuild ALL_BUILD.vcxproj /P:Configuration=Release
      - name: Test P(NG)Convert
        run: |
          bin/pconvert version
